- name: create user if not exists
  hosts: targets
  tasks:
    - name: "check user exists..?"
      command: id roboshop
      register: command_output
      # This command only checks the user, so do not mark the task as changed.
      changed_when: false
      # If the user does not exist, id returns non-zero. That is expected here.
      failed_when: false

    - name: "print output"
      debug:
        var: command_output

    - name: "create user"
      become: true
      command: useradd roboshop
      when: command_output.rc != 0
