- name: take var values from inventory file
  hosts: local
  vars:
    st_name : jansi
  tasks:
     - name: varables from inventory
       debug:
          msg: "my name is {{ st_name }} i am from {{ city }} i am studying {{ course }}"


# ansible-playbook -i inventory.ini -e "city=hyd course=aiops" extra-vars.yaml