- name: filter on list
  hosts: local
  vars:
   list1:
     - 41
     - 21
     - 3
     - 16
     - 41
  tasks:
   - name: "length of list {{ list1 }}"
     debug:
       msg: "length of {{ list1 }} is {{ list1 | length }}"
       
   - name: "first element of list {{ list1 }}"
     debug:
       msg: "first element of list {{ list1 }} is  {{ list1 | first }}"  

   - name: "last element of list {{ list1 }}"
     debug:
       msg: "last element of list {{ list1 }} is  {{ list1 | last }}"

   - name: "sort elements of list {{ list1 }}"
     debug:
       msg: "sort element of list {{ list1 }} is  {{ list1 | sort }}"
       
   - name: "reverse elements of list {{ list1 }}"
     debug:
       msg: "reverse elements of list {{ list1 }} are  {{ list1 | reverse }}"

   - name: "unique element of list {{ list1 }}"
     debug:
       msg: "unique elements of list {{ list1 }} is  {{ list1 | unique }}"                               