- name: convert list to dict
  hosts: local
  vars:
    list1:
      - key: x
        value: 1
      - key: y
        value: 2
    dict1:
      x: 1
      y: 2
  tasks:
    - name: converting list to dict
      debug:
        msg: "{{ list1 | items2dict }}"

    - name: converting dict to list
      debug:
        msg: "{{ dict1 | dict2items }}"
