- name: aceessing list of dictonary
  hosts: local
  vars:
    users:
      - student: jansi
        age: 25
      - student: munni
        age: 23
  tasks:
    - name: access values
      debug:
         msg: "name is {{ item.student }} and age is {{ item.age }}"
      loop: "{{ users }}"
