---
- name: installing maven
  hosts: targets
  become: true
  vars: 
    pkg : maven
  tasks:
    - name : instaling maven on target hosts
      dnf:
        name : "{{ pkg }}" 
        state : present