- name: access varaible from files
  hosts: local
  vars:
     name : jansi
  vars_files:
      - fileofvar.yaml
  tasks:
    - name: which course are you learning
      debug:
        msg: "{{ name }} is learning {{ course }} at {{ city }} for cost of {{ fee }}"   