- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
    - name: disbale default nginx
      command: dnf module disable nginx -y
    - name: enable nginx version specific
      command: dnf module enable nginx -y
    - name: install nginx
      dnf:
       state: present
       name: nginx
    - name: service restart
      service:
       name: nginx
       state: started
       enabled: true
               