[mongodb]
mongodb.jansi.fun

[redis]
redis.jansi.fun

[rabbitmq]
rabbit.jansi.fun

[mysql]
mysql.jansi.fun

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321

[local]
localhost ansible_connection=local
; do not SSH, run directly on my Mac
